FoskorSecurityTransport/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoskorSecurityTransport.Models;
using PagedList;

namespace FoskorSecurityTransport.Controllers
{
    public class DepartmentsController : Controller
    {
        private SecurityTransportTestEntities db = new SecurityTransportTestEntities();

        // GET: Departments

            public ActionResult Index(int page = 1)
            {
                int pageSize = 3;
                return View(db.Departments.OrderByDescending(x=>x.DepartmentName).ToPagedList(page, pageSize));
            }



        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentID,DepartmentName,Status")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentID,DepartmentName,Status")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoskorSecurityTransport/Controllers/TripsController.cs
using FoskorSecurityTransport.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;



namespace FoskorSecurityTransport.Controllers
{
    public class TripsController : Controller
    {
        private SecurityTransportTestEntities db = new SecurityTransportTestEntities();
        private Vehicle dbVehicle = new Vehicle();

        // GET: Trips
        public ActionResult Index(int page=1)
        {
            int pageSize = 10;
            return View(db.Trips.OrderByDescending(x => x.DateOut).ToPagedList(page, pageSize));
          
        }

        // GET: Trips/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // GET: Trips/Create
        public ActionResult Create()
        {
            var VMake = db.Vehicles.ToList();
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TripID,DateOut,DateIn,StartingPoint,Passenger1,CompanyNumber1,Destination1,Passenger2,CompanyNumber2,Destination2,Passenger3,CompanyNumber3,Destination3,Passenger4,CompanyNumber4,Destination4,Department1,Supervisor1,Reason,Driver,Vehicle,KMOut,KMIn,TotalKMs,TimeOut,TimeIn,Status,SDateTime,Capturer,Supervisor2,Supervisor3,Supervisor4,Department2,Department3,Department4,noOfPassengers")] Trip trip)
        {
            {
                                 
                db.Trips.Add(trip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trip);
        }


        // GET: Trips/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TripID,DateOut,DateIn,StartingPoint,Passenger1,CompanyNumber1,Destination1,Passenger2,CompanyNumber2,Destination2,Passenger3,CompanyNumber3,Destination3,Passenger4,CompanyNumber4,Destination4,Department1,Supervisor1,Reason,Driver,Vehicle,KMOut,KMIn,TotalKMs,TimeOut,TimeIn,Status,SDateTime,Capturer,Supervisor2,Supervisor3,Supervisor4,Department2,Department3,Department4,noOfPassengers")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trip trip = db.Trips.Find(id);
            db.Trips.Remove(trip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoskorSecurityTransport/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing.Printing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoskorSecurityTransport.Models;
using PagedList;

namespace FoskorSecurityTransport.Controllers
{
    public class VehiclesController : Controller
    {
        private SecurityTransportTestEntities db = new SecurityTransportTestEntities();

        // GET: Vehicles
        public ActionResult Index(int page=1)
        {
            int pageSize = 10;
            return View(db.Vehicles.OrderByDescending(x => x.Status).ToPagedList(page, pageSize));

        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleID,RegistrationNo,Make,Model,Status")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleID,RegistrationNo,Make,Model,Status")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoskorSecurityTransport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />  
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" type="text/css" href="~/StyleSheet1.css" >
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <img src="~/Content/foskor.jpg" />
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Security Appplication", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Security Transport Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-2.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript">
        console.log('js loaded')
        $(document).ready(function () {
            $('.table').DataTable({ dom: 'Bfrtip', "buttons": ['excel'] });
            $('.table a').addClass("btn btn-primary");
            $('.container p>a').addClass("btn btn-primary");
        });
    </script>
</body>
</html>

FoskorSecurityTransport/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>
        <link rel="stylesheet" type="text/css" href="~/StyleSheet1.css" >*@

    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/_DisplayTheme/css/bootstrap.min.css" rel="stylesheet" />
    <!-- bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="~/Content/_DisplayTheme/css/bootstrap-theme.css" rel="stylesheet" />
    <!--external css-->
    <!-- font icon -->
    <link href="css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/Content/_DisplayTheme/css/elegant-icons-style.css" rel="stylesheet" />

    <link href="css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/_DisplayTheme/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="css/style.css" rel="stylesheet">
    <link href="~/Content/_DisplayTheme/css/style.css" rel="stylesheet" />

    <link href="css/style-responsive.css" rel="stylesheet" />
    <link href="~/Content/_DisplayTheme/css/style-responsive.css" rel="stylesheet" />

    <script src="~/Content/_DisplayTheme/js/jquery-1.8.2.js"></script>
    @*<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>*@
    <script type="text/javascript">
        $(function () {
            $('#chkStatus').change(function () {
                if ($('#chkStatus').is(':checked'))
                    $("#pasenger2").fadeIn();
                else
                    $('#pasenger2').fadeOut();
            });
        });
    </script>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#chkPassanger2").click(function () {
                if ($(this).is(":checked")) {
                    $("#dvPass2").show();
                } else {
                    $("#dvPass2").hide();
                }
            });
        });

        $(function () {
            $("#chkPass3").click(function () {
                if ($(this).is(":checked")) {
                    $("#dvPass3").show();
                } else {
                    $("#dvPass3").hide();
                }
            });
        });

        $(function () {
            $("#chkPass4").click(function () {
                if ($(this).is(":checked")) {
                    $("#dvPass4").show();
                } else {
                    $("#dvPass4").hide();
                }
            });
        });

    </script>



    <!-- container section start -->
    <section id="container" class="">
        <!--header start-->

        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="">
                        <a class="" href="index.html">
                            <i class="icon_house_alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_document_alt"></i>
                            <span>Trips</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">

                            <li>@Html.ActionLink("Create trip", "Create", "Trips")</li>
                            <li>@Html.ActionLink("View trips", "Index", "Trips")</li>
                            @*<li>@Html.ActionLink("View trip", "Index", "Trips")</li>*@
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon-form-l"></i>
                            <span>Departments</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li>@Html.ActionLink("View Departments", "Index", "Departments")</li>
                            <li>@Html.ActionLink("Add Department", "Create", "Departments")</li>

                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_book"></i>
                            <span>Vehicles</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            <li>@Html.ActionLink("View Vehicles", "Index", "Vehicles")</li>
                            <li>@Html.ActionLink("Add Vehicle", "Create", "Vehicles")</li>

                        </ul>
                    </li>
                    @*<li>
                            <a class="" href="widgets.html">
                                <i class="icon_genius"></i>
                                <span>Widgets</span>
                            </a>
                        </li>
                        <li>
                            <a class="" href="chart-chartjs.html">
                                <i class="icon_piechart"></i>
                                <span>Charts</span>

                            </a>

                        </li>

                        <li class="sub-menu">
                            <a href="javascript:;" class="">
                                <i class="icon_table"></i>
                                <span>Tables</span>
                                <span class="menu-arrow arrow_carrot-right"></span>
                            </a>
                            <ul class="sub">
                                <li><a class="" href="basic_table.html">Basic Table</a></li>
                            </ul>
                        </li>

                        <li class="sub-menu ">
                            <a href="javascript:;" class="">
                                <i class="icon_documents_alt"></i>
                                <span>Pages</span>
                                <span class="menu-arrow arrow_carrot-right"></span>
                            </a>
                            <ul class="sub">
                                <li><a class="" href="profile.html">Profile</a></li>
                                <li><a class="" href="login.html"><span>Login Page</span></a></li>
                                <li><a class="active" href="blank.html">Blank Page</a></li>
                                <li><a class="" href="404.html">404 Error</a></li>
                            </ul>
                        </li>*@

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!-- page start-->
                @RenderBody()
                <!-- page end-->
            </section>
        </section>
        <!--main content end-->
    </section>

    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Security Transport Application</p>
            </footer>
        </div>*@


    <script src="js/jquery.js"></script>
    <script src="~/Content/_DisplayTheme/js/jquery.js"></script>

    <script src="js/bootstrap.min.js"></script>
    <script src="~/Content/_DisplayTheme/js/bootstrap.min.js"></script>
    <!-- nice scroll -->
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/_DisplayTheme/js/jquery.scrollTo.min.js"></script>

    <script src="js/jquery.nicescroll.js" type="text/javascript"></script><!--custome script for all page-->
    <script src="~/Content/_DisplayTheme/js/jquery.nicescroll.js"></script>


    <script src="js/scripts.js"></script>
    <script src="~/Content/_DisplayTheme/js/scripts.js"></script>
    <script type="text/javascript">
        console.log('js loaded')
        $(document).ready(function () {
            $('.table').DataTable({ dom: 'Bfrtip', "buttons": ['excel'] });
            $('.table a').addClass("btn btn-primary");
            $('.container p>a').addClass("btn btn-primary");
        });
    </script>

    @*<script src="~/Scripts/jquery-2.0.0.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
        <script type="text/javascript">
            console.log('js loaded')
            $(document).ready(function () {
                $('.table').DataTable({ dom: 'Bfrtip', "buttons": ['excel'] });
                $('.table a').addClass("btn btn-primary");
                $('.container p>a').addClass("btn btn-primary");
            });
        </script>*@
    </body>
</html>